-- Real CyberSachet curriculum, seeding the courses/lessons/quiz_questions
-- schema from migration 0037. This is the exact same content shipped as a
-- local-storage-backed preview in frontend/src/data/cybersachetCourses.js —
-- once this migration is applied and an organization is licensed for
-- 'cybersachet' (organization_products), CyberSachetTraining.jsx switches
-- from the local preview to these real, database-backed courses
-- automatically; nothing in the frontend needs to change.

insert into cybersachet_courses (slug, title, description, level, estimated_minutes, sort_order) values
  ('phishing-awareness', 'Phishing Awareness', 'Recognize the emails, texts, and calls attackers use to steal credentials — and what to do the moment you suspect one.', 'beginner', 15, 0),
  ('password-security-mfa', 'Password Security & MFA', 'Why passwords keep failing organizations, and the two habits — passphrases and multi-factor authentication — that actually stop account takeovers.', 'beginner', 12, 1),
  ('social-engineering', 'Social Engineering', 'Phishing''s cousins — impersonation calls, tailgating, and pretexting — and the habits that catch a manipulation attempt before it works.', 'intermediate', 15, 2),
  ('malware-ransomware', 'Malware & Ransomware', 'How viruses, trojans, and ransomware actually get in, what makes ransomware uniquely dangerous, and the habits that stop an infection from spreading.', 'intermediate', 14, 3),
  ('data-handling-privacy', 'Data Handling & Privacy', 'How to classify, share, and store sensitive data safely — and what to do the moment you suspect something''s gone wrong.', 'intermediate', 12, 4)
on conflict (slug) do nothing;

insert into cybersachet_lessons (course_id, title, body, sort_order)
select c.id, l.title, l.body, l.sort_order
from cybersachet_courses c
join (values
  ('phishing-awareness', 'What phishing actually is', 'Phishing is a message designed to make you act before you think — click a link, open an attachment, or hand over a password — by impersonating someone or something you trust: your bank, your IT department, a delivery company, even a coworker. It doesn''t need to fool everyone. Out of a thousand emails, attackers only need a handful of clicks to get a foothold. That''s why it''s the single most common way organizations get breached — not sophisticated hacking, just one tired click on a Monday morning.', 0),
  ('phishing-awareness', 'The red flags that give it away', 'Urgency and fear are the biggest tells: "Your account will be suspended in 24 hours," "Unusual sign-in detected," "Invoice overdue — pay now." Real IT and finance departments rarely operate on a countdown timer. Other signals: a sender address that''s almost right (support@paypa1.com), a generic greeting instead of your name, a link where the visible text doesn''t match where it actually goes (hover before you click), and requests to do something outside the normal process — like a CEO suddenly emailing you personally to buy gift cards.', 1),
  ('phishing-awareness', 'If you already clicked', 'Don''t panic, and don''t hide it. Disconnect the device from Wi-Fi if you can do it immediately. If you entered a password, change it right away — on that site and anywhere else you reused it. Report it to your IT/security contact immediately; the faster they know, the smaller the blast radius. Every real incident response process assumes people will click sometimes — the only mistake that makes things worse is staying quiet about it.', 2),
  ('phishing-awareness', 'Building a verify-first habit', 'Before acting on an unexpected request — a password reset, a wire transfer, a link to "review a document" — verify through a second channel you already trust: call the person back on a known number, check the vendor portal directly instead of clicking the email link, or ask a coworker in person or on Slack. This single habit defeats the vast majority of phishing, because attackers are counting on you to act in the moment, not to pause and check.', 3),

  ('password-security-mfa', 'Why passwords fail', 'Most account breaches don''t come from someone guessing your password character by character — they come from reuse. If one site you use gets breached and your password leaks, attackers automatically try that same email/password pair on banks, email providers, and work accounts. A single reused password can turn one small breach into a dozen compromised accounts. Complexity rules ("one number, one symbol") mostly just make passwords harder to remember without making them meaningfully harder to crack — length and uniqueness matter far more.', 0),
  ('password-security-mfa', 'Passphrases beat passwords', 'A long, random passphrase like "correct-horse-battery-staple-42" is both easier to remember and far harder to crack than "P@ssw0rd1!" — length is what defeats modern cracking hardware, not symbol-stuffing. The best passwords, though, are ones you never have to remember at all: fully random strings generated and stored by a password manager. Reserve your own memory for one strong master passphrase that unlocks the manager.', 1),
  ('password-security-mfa', 'Password managers, in practice', 'A password manager generates a unique, random password for every single account and fills it in for you — so reuse becomes physically impossible instead of just discouraged. If your organization provides one, use it for every account, personal accounts included; a breach of your personal email is often the first domino toward a work account breach through password-reset links.', 2),
  ('password-security-mfa', 'Multi-factor authentication (MFA)', 'MFA means proving who you are with something beyond a password — a code from an app, a hardware key, a push notification. Even if an attacker steals your password, they''re stopped cold without the second factor. An authenticator app or hardware key is meaningfully stronger than SMS codes, which can be intercepted through SIM-swapping — but any MFA is dramatically better than none. Turn it on everywhere it''s offered, starting with email, since email is usually the master key to resetting everything else.', 3),

  ('social-engineering', 'Pretexting and impersonation', 'Pretexting is inventing a believable scenario to extract information or access: someone calling as "IT support" needing your password to "fix an urgent issue," or a fake vendor invoice referencing a real project name they found on LinkedIn. The details make it convincing — attackers research their target first. The defense isn''t suspicion of everyone; it''s a fixed rule: legitimate IT, finance, or leadership will never ask you to bypass normal verification steps, no matter how urgent they sound.', 0),
  ('social-engineering', 'Vishing and smishing', 'Vishing (voice phishing) and smishing (SMS phishing) move the same tricks to phone calls and texts, where people tend to be less guarded than with email. A call claiming to be your bank''s fraud department, or a text about a "missed delivery" with a link — both are designed to create urgency in a channel with less scrutiny. Treat unexpected calls and texts asking for information or action with the same skepticism as email: hang up and call the organization back using a number you already know, not one they gave you.', 1),
  ('social-engineering', 'Tailgating and physical social engineering', 'Not every attack is digital. Tailgating is following an employee through a badge-locked door without swiping in yourself, relying on politeness — most people hold the door. A confident walk and a plausible reason ("forgot my badge, running late") gets further than you''d expect. The fix is a workplace norm, not paranoia: it''s normal and expected to politely ask an unfamiliar person to badge in themselves, even if it feels awkward.', 2),
  ('social-engineering', 'Building a verify-first habit at work', 'The common thread across every social engineering tactic is manufactured urgency plus a request to skip a normal step. The single strongest defense across email, phone, and in-person: when something feels rushed or exceptions-required, pause and verify through an independent, known channel before acting — and know that reporting a suspicious attempt, even if you''re not sure, is always the right call.', 3),

  ('malware-ransomware', 'Malware, in plain terms', 'Malware is any software built to damage, spy on, or take control of a system without permission — the umbrella term covering viruses, worms, trojans, spyware, and ransomware. A virus attaches itself to a legitimate file and spreads when that file is shared or run. A worm spreads on its own across a network with no user action needed. A trojan disguises itself as something useful — a "free" tool, a cracked application, an invoice attachment — to trick you into installing it yourself. Different mechanisms, same goal: get code running on a machine it doesn''t belong on.', 0),
  ('malware-ransomware', 'How it actually gets in', 'The overwhelming majority of malware infections start with a person, not a technical exploit: an email attachment opened, a link to a fake software download, a USB drive plugged in out of curiosity, or a legitimate-looking browser update prompt that isn''t real. Outdated software is the second major door — unpatched operating systems and applications have known holes that malware is built specifically to walk through. Keeping software updated and thinking twice before opening an unexpected attachment closes both doors at once.', 1),
  ('malware-ransomware', 'Why ransomware is different', 'Ransomware encrypts your files — and often every file it can reach on connected network drives — then demands payment for the decryption key. It''s uniquely dangerous because it doesn''t quietly steal data in the background; it stops a business cold, often across every department at once, within minutes of detonating. Paying the ransom is never guaranteed to restore your files and directly funds the next attack. The only reliable defense is prevention plus real, tested backups kept disconnected from the network — a ransomware infection that hits a current, isolated backup is a bad afternoon; one that doesn''t is a company-ending event.', 2),
  ('malware-ransomware', 'If you suspect an infection', 'Disconnect the device from the network immediately — unplug the cable or turn off Wi-Fi — to stop it from spreading to shared drives or other machines before you do anything else. Don''t restart the computer; some malware activates further damage on reboot, and a live memory dump can help investigators understand what happened. Report it to IT/security right away, even if you''re not certain — the earlier containment starts, the smaller the damage. As with phishing, speed and honesty beat trying to quietly fix it yourself.', 3),

  ('data-handling-privacy', 'Classifying sensitive data', 'Not all data carries the same risk. Customer PII (names, emails, payment details), credentials, and internal financial data need the most care; general internal docs need some care; public marketing material needs none. When you''re not sure how sensitive something is, treat it as sensitive by default and ask — the cost of an unnecessary precaution is minutes; the cost of a real leak is measured in trust and, often, regulatory fines.', 0),
  ('data-handling-privacy', 'Safe sharing and storage', 'Share sensitive files through your organization''s approved tools — not personal email or personal cloud storage, which fall outside company security controls entirely. Before sharing a link, double-check the permissions: "anyone with the link" often means anyone on the internet who ever sees that link, forwarded or not. Set expiration dates on shared links where possible, and remove access once a project wraps up rather than leaving it open indefinitely.', 1),
  ('data-handling-privacy', 'Working remotely and securely', 'Public Wi-Fi at a cafe or airport is not inherently unsafe with modern encrypted sites (https), but avoid sensitive work on networks you don''t control without your company''s VPN if one is provided. Lock your screen every time you step away, even for a minute — in an office or in public. Never let sensitive data live only on a personal device; if you wouldn''t want it on the news, it shouldn''t be sitting in your personal Downloads folder.', 2),
  ('data-handling-privacy', 'Reporting a suspected breach', 'If you send sensitive data to the wrong person, lose a device, or notice data somewhere it shouldn''t be, report it immediately — even if you''re not fully sure it''s a real problem. Every hour matters for containment, and organizations plan for mistakes; what they can''t plan for is not knowing. Nobody gets in trouble for reporting a real mistake quickly. The trouble comes from staying quiet and hoping no one notices.', 3)
) as l(course_slug, title, body, sort_order) on l.course_slug = c.slug
where not exists (select 1 from cybersachet_lessons existing where existing.course_id = c.id and existing.title = l.title);

insert into cybersachet_quiz_questions (course_id, question, choices, correct_index, sort_order)
select c.id, q.question, q.choices::jsonb, q.correct_index, q.sort_order
from cybersachet_courses c
join (values
  ('phishing-awareness', 'What''s the single biggest tell of a phishing message?', '["A logo that looks slightly different", "Artificial urgency pushing you to act immediately", "The email arrived outside business hours", "It was sent to multiple people"]', 1, 0),
  ('phishing-awareness', 'You hover over a link and the URL doesn''t match the text. What should you do?', '["Click it carefully, just don''t enter any passwords", "Forward it to a friend to check", "Don''t click — treat the mismatch as a red flag", "Reply asking the sender to confirm"]', 2, 1),
  ('phishing-awareness', 'You realize you just entered your password on a fake login page. First move?', '["Wait and see if anything happens", "Change that password immediately and report it", "Delete the email and move on", "Only worry if you get a strange notification"]', 1, 2),
  ('phishing-awareness', 'A "verify-first" habit means:', '["Trusting any email that looks professionally designed", "Confirming unexpected requests through a separate, known channel", "Only opening emails from contacts already in your address book", "Reporting every single email to IT before reading it"]', 1, 3),

  ('password-security-mfa', 'What makes password reuse so dangerous?', '["It''s against most company policies", "One leaked password can unlock many of your accounts at once", "It makes passwords easier to guess character by character", "It slows down your login speed"]', 1, 0),
  ('password-security-mfa', 'What matters most for password strength?', '["Using at least one special character", "Changing it every 30 days", "Length and uniqueness", "Including your birth year"]', 2, 1),
  ('password-security-mfa', 'Why turn on MFA even if you have a strong password?', '["It''s required for password managers to work", "It stops an attacker even if your password is stolen", "It makes your password expire less often", "It replaces the need for a password entirely"]', 1, 2),
  ('password-security-mfa', 'Which MFA method is generally weakest against a determined attacker?', '["Hardware security key", "Authenticator app code", "SMS text message code", "Biometric (fingerprint/face)"]', 2, 3),

  ('social-engineering', 'What is pretexting?', '["A type of firewall configuration", "Inventing a believable scenario to extract information or access", "A password complexity rule", "An automated phishing filter"]', 1, 0),
  ('social-engineering', 'You get an unexpected call from "your bank''s fraud department" asking to confirm your login details. Best move?', '["Give the details since it''s about fraud protection", "Hang up and call the bank back on a number you already know", "Ask them to email you instead", "Give partial information only"]', 1, 1),
  ('social-engineering', 'What is tailgating in a security context?', '["Speeding in a company vehicle", "Following someone through a secured door without badging in", "Sending rapid-fire phishing emails", "Monitoring network traffic"]', 1, 2),
  ('social-engineering', 'The common thread across most social engineering attacks is:', '["Poor grammar in the message", "Manufactured urgency plus a request to skip a normal step", "Attacks only happen over email", "They only target senior executives"]', 1, 3),

  ('malware-ransomware', 'What''s the key difference between a worm and a trojan?', '["A worm spreads on its own; a trojan tricks you into installing it", "A trojan is always more destructive", "A worm only affects mobile devices", "There is no meaningful difference"]', 0, 0),
  ('malware-ransomware', 'What are the two most common ways malware actually gets onto a system?', '["Weak Wi-Fi passwords and old hardware", "Human action (attachments/links/downloads) and outdated, unpatched software", "Malware only spreads through physical USB drives", "It requires a targeted hacker, not routine behavior"]', 1, 1),
  ('malware-ransomware', 'Why is ransomware considered uniquely dangerous compared to other malware?', '["It only targets large enterprises", "It quietly steals data without anyone noticing", "It can halt an entire organization within minutes and paying doesn''t guarantee recovery", "It''s the easiest malware type to remove"]', 2, 2),
  ('malware-ransomware', 'You suspect your computer is infected with ransomware. First move?', '["Restart the computer to clear it", "Disconnect from the network immediately and report it", "Wait to see if it spreads further before acting", "Try to pay the ransom quickly to minimize downtime"]', 1, 3),

  ('data-handling-privacy', 'When you''re unsure how sensitive a piece of data is, you should:', '["Assume it''s not sensitive to save time", "Treat it as sensitive by default and ask", "Only worry about it if it contains a password", "Check with a coworker informally, no need to escalate"]', 1, 0),
  ('data-handling-privacy', 'What''s the risk with "anyone with the link" sharing settings?', '["The file becomes read-only", "The link can end up accessible to anyone it''s forwarded to", "It automatically expires after a week", "It only works within your company''s network"]', 1, 1),
  ('data-handling-privacy', 'On public Wi-Fi, the safest approach for sensitive work is:', '["Any https site is automatically fine, no precautions needed", "Avoid sensitive work unless using your company''s VPN", "Public Wi-Fi is never safe for any browsing", "Only avoid it if using a work laptop"]', 1, 2),
  ('data-handling-privacy', 'You accidentally email a sensitive file to the wrong person. Best move?', '["Wait to see if they notice or respond", "Report it immediately, even without full certainty of impact", "Only report it if the file contained passwords", "Quietly try to recall the email and say nothing else"]', 1, 3)
) as q(course_slug, question, choices, correct_index, sort_order) on q.course_slug = c.slug
where not exists (select 1 from cybersachet_quiz_questions existing where existing.course_id = c.id and existing.question = q.question);
