-- One comprehension-check question per lesson, matching the content shipped
-- as the local-storage preview in frontend/src/data/cybersachetCourses.js.
-- Matched by course slug + lesson title, same pattern as 0039/0040.

update cybersachet_lessons l set
  check_question = q.question, check_choices = q.choices::jsonb, check_correct_index = q.correct_index
from cybersachet_courses c, (values
  ('phishing-awareness', 'What phishing actually is', 'Why is phishing effective even though it doesn''t fool everyone?', '["It always uses malware", "Attackers only need a small number of clicks to succeed", "It exclusively targets executives", "It requires no technical skill at all"]', 1),
  ('phishing-awareness', 'The red flags that give it away', 'Which of these is described as one of the biggest phishing tells?', '["A long email signature", "Manufactured urgency or fear", "Perfect spelling and grammar", "An email sent during business hours"]', 1),
  ('phishing-awareness', 'If you already clicked', 'What should you do first if you already clicked a phishing link?', '["Wait to see if anything bad happens", "Disconnect from the network and change any entered passwords", "Delete the email and say nothing", "Restart your computer right away"]', 1),
  ('phishing-awareness', 'Building a verify-first habit', 'What is the "verify-first" habit described in this lesson?', '["Verifying your own identity to IT before logging in", "Confirming unexpected requests through a separate, already-trusted channel", "Verifying an email''s spelling before reading it", "Checking your spam folder daily"]', 1),

  ('password-security-mfa', 'Why passwords fail', 'Why is password reuse so dangerous, per this lesson?', '["It''s against most companies'' style guide", "One leaked password can be tried across many other accounts", "It makes typing slower", "It voids warranty on hardware"]', 1),
  ('password-security-mfa', 'Passphrases beat passwords', 'What makes a passphrase stronger than a short complex password?', '["It contains more special characters", "Its length defeats cracking hardware better than symbol-stuffing", "It''s changed more frequently", "It''s shorter and easier to type"]', 1),
  ('password-security-mfa', 'Password managers, in practice', 'What does a password manager do that stops password reuse?', '["It reminds you to reuse strong passwords", "It generates and stores a unique random password for every account", "It deletes old passwords automatically", "It only works for work accounts"]', 1),
  ('password-security-mfa', 'Multi-factor authentication (MFA)', 'Why is an authenticator app stronger than SMS codes for MFA?', '["SMS codes cost money to receive", "SMS codes can be intercepted through SIM-swapping", "Authenticator apps work without a phone", "SMS codes never expire"]', 1),

  ('social-engineering', 'Pretexting and impersonation', 'What''s the fixed rule this lesson recommends against pretexting?', '["Never answer the phone from unknown numbers", "Legitimate IT/finance/leadership will never ask you to bypass normal verification steps", "Always ask for a callback number", "Report every phone call to security"]', 1),
  ('social-engineering', 'Vishing and smishing', 'You get an unexpected call from your "bank''s fraud department" asking for login details. Best move?', '["Provide the details since it''s about fraud protection", "Hang up and call the bank back using a number you already know", "Ask them to text you instead", "Give them half the information"]', 1),
  ('social-engineering', 'Tailgating and physical social engineering', 'What''s the recommended workplace norm around tailgating?', '["Never hold the door for anyone", "It''s normal and expected to ask an unfamiliar person to badge in themselves", "Always assume visitors are safe", "Report tailgating only if a badge alarm sounds"]', 1),
  ('social-engineering', 'Building a verify-first habit at work', 'What''s the common thread across social engineering tactics, per this lesson?', '["They always involve email", "Manufactured urgency plus a request to skip a normal step", "They only target new employees", "They require advanced hacking tools"]', 1),

  ('malware-ransomware', 'Malware, in plain terms', 'What''s the key difference between a worm and a trojan?', '["A worm spreads on its own; a trojan tricks you into installing it", "A trojan is always more destructive", "A worm only affects mobile devices", "There is no meaningful difference"]', 0),
  ('malware-ransomware', 'How it actually gets in', 'What are the two most common doors malware uses to get in?', '["Weak Wi-Fi and old hardware", "Human action (attachments/links) and outdated, unpatched software", "Malware only spreads via USB", "It always requires a targeted hacker"]', 1),
  ('malware-ransomware', 'Why ransomware is different', 'What''s described as the only reliable defense against ransomware?', '["Paying quickly to minimize damage", "Prevention plus real, tested backups kept disconnected from the network", "Using a stronger antivirus alone", "Ignoring the ransom note"]', 1),
  ('malware-ransomware', 'If you suspect an infection', 'What should you NOT do if you suspect a ransomware infection?', '["Disconnect from the network", "Report it to IT/security", "Restart the computer right away", "Act quickly"]', 2),

  ('data-handling-privacy', 'Classifying sensitive data', 'What should you do when you''re unsure how sensitive a piece of data is?', '["Assume it''s not sensitive to save time", "Treat it as sensitive by default and ask", "Only worry about it if it contains a password", "Ignore it until someone complains"]', 1),
  ('data-handling-privacy', 'Safe sharing and storage', 'What''s the risk with "anyone with the link" sharing settings?', '["The file becomes read-only", "The link can end up accessible to anyone it''s forwarded to", "Files expire automatically", "It only works inside the company network"]', 1),
  ('data-handling-privacy', 'Working remotely and securely', 'What does this lesson recommend for sensitive work on public Wi-Fi?', '["Any https site is automatically safe, no precautions needed", "Avoid sensitive work unless using your company''s VPN", "Public Wi-Fi is always completely safe", "Only avoid it on weekends"]', 1),
  ('data-handling-privacy', 'Reporting a suspected breach', 'What does this lesson say about reporting a mistake, like emailing sensitive data to the wrong person?', '["Wait to see if anyone notices", "Report it immediately, even without full certainty of impact", "Only report if it contained passwords", "Try to quietly recall the email and say nothing else"]', 1)
) as q(course_slug, lesson_title, question, choices, correct_index)
where c.slug = q.course_slug and l.course_id = c.id and l.title = q.lesson_title;
